version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_kkc_network
    volumes:
      - gis_kkc_media:/data/media/
      - gis_kkc_static:/data/static/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis_kkc_django:5
    networks:
      - gis_kkc_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis_kkc_static:/home/gis_1ban_01/staticfiles/
      - gis_kkc_media:/home/gis_1ban_01/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_kkc_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gis_kkc_network:

volumes:
  gis_kkc_static:
  gis_kkc_media:
  gis_mariadb:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true